### ISSUE TITLE
Secure library.kiwix.org catalog part (create dedicated Docker instance)

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/container-images#147]
https://library.kiwix.org use `kiwix-serve` to provide two main types of content:

- The catalog part (opds feeds, search for zim file according the criteria, ...)
- The zim content part (main page, zim articles, fulltext search, ...).

They are both served by `kiwix-serve` (through `kiwix-lib`) but it follow to different code path:

- The catalog part mainly (if not only) works on the `library.xml` as source content. It main works is mainly to parse the request and generate the corresponding opds feed. No use of the `libzim` is made.
- On the opposite side, the content part greatly use the libzim. It is time consuming and is greatly subject to evolution of the libzim (and its potential bugs).

On top of that, the catalog part is a mandatory piece of our system as it is used by our client softwares to get the list of available zim files and the url to download them. The content part is "only" used as a demo of our technology/catalog.
(Not that the content part is not important. It is important that everything works correctly and we fix (performance) issues. But one part is mandatory (a dependency) and the other not)

Having the two part served by the same process can lead to the catalog part being break because of a issue not related to it or simply because of too much requests on the content part.

The solution I propose is to split the two part in to different processes.
It could be in two different binaries or we could keep `kiwix-serve` but launch two processes with different options. This way, if the content part crash or take too much time, the catalog part would still be available.
It would be to the proxy to forward `https://library.kiwix.org/catalog/...` requests to the catalog process and other requests to the content process.

**Comment by kelson42** [comment]
@rgaudin Sounds the right moment to do it (within k8s project).

**Comment by rgaudin** [comment]
Ah right! We were discussing exactly this the other and there's already an old ticket. Am I right to assume that both would work on the same domain (`library.kiwix.org`) and we'd have the `/catalog` prefix for the lightweight OPDS container and the rest on the files-backed content container?

**Comment by kelson42** [comment]
@rgaudin I'm not 100% sure, but I guess the catalog container would have only the `library.xml` to feed the OPDS. Any request to read the content would failed. The content containter would have everything like today. The reverse proxy would route all OPDS requests to the catalog container and otherwise to the content container.

**Comment by rgaudin** [comment]
Yes, that's why I want you to confirm that all OPDS resources are prefixed under /catalog and that those only require the library to work.

**Comment by kelson42** [comment]
@rgaudin Yes they are AFAIK but tgis still need to be properly documented.

**Comment by rgaudin** [comment]
OK, who's able to confirm? @veloman-yunkan ?

**Comment by veloman-yunkan** [comment]
This is a good idea, but the reality is a little more complex. Currently we have the following endpoints:

- `/catalog/` - no dependence on libzim
- `/skin/` - no dependence on libzim
- `/catch/external` - no dependence on libzim
- `/search` - this is a mixed endpoint, because there are two kind of searches - full-text search in a book (which depends on libzim) and search in library (which doesn't)
- `/suggest` - this is a purely content-related endpoint
- `/random` - this is a purely content-related endpoint
- `/raw/` - this is a purely content-related endpoint
- `/`*ANYTHING_ELSE* - content (access to books is through top-level urls, which prevents having books with names coinciding with the API endpoint names; probably, not a big issue but, nevertheless, not the best design choice)

**Comment by rgaudin** [comment]
Thanks for the break down ; am I right to assume we can easily serve the OPDS by just forwarding `/catalog` to a dedicated kiwix-serve only fed with a `library.xml` ?

**Comment by veloman-yunkan** [comment]
That's correct. But it also make sense to forward `/skin`, `/catch` and half of `/search' to the same `kiwix-serve` instance.

**Comment by rgaudin** [comment]
OK I understand your point but from my point of view, OPDS is mission critical as it is used directly by at least all iOS users and kiwix-desktop users I think (and more to come) while `library.kiwix.org` is a demo that is important but only affects itself.

So my strategy would be to serve the least required for the OPDS to work, which would be `/catalog`.

A varnish or a better cache would relieve the main kiwix-serve on `/skin`. `/catch` is not a concern on this particular instance.

As for `/search`, its only use if for the demo so I wouldn't involve the OPDS-only container (although some requests don't require libzim). Might also be tricky to dispatch requests. I believe the distinction is done via some query param.

If your concern regards the performance of the main demo kiwix-serve, I believe it might be more efficient to use multiple instances of the demo kiwix-serve instead of offloading some endpoints to the OPDS-only container.

**Comment by kelson42** [comment]
@rgaudin @veloman-yunkan My worry is that the `/search` backen has a part for the `catalog` container and a part for the `demo` container... and that it is not clear how to make the difference to me for now in the reverse-proxy.

**Comment by rgaudin** [comment]
As there is no documentation, it's difficult for me to understand what feature we are talking about :
- is it a UI feature that happens to return results only from the catalog? In that case, it's no concern for OPDS-only container as the ZIM-backed container will obviously also have a library.
- Is it an OPDS feature that is exposed in (or advertised at) a different endpoint?

**Comment by veloman-yunkan** [comment]
`/search` without a `?content=bookname` parameter is a UI feature that happens to return results only from the catalog.

**Comment by veloman-yunkan** [comment]
Oops. My analysis of the `/search` endpoint was totally flawed. I am so ashamed and sorry. `/search` without a `?content=bookname` parameter is multi-ZIM search.

**Comment by rgaudin** [comment]
OK Thanks ; it's still a UI feature in that it returns an HTML response with the multi-zim results (which rarely happens online due to the number of ZIMs anyway) so it's not related to OPDS-only operations.

**Comment by mgautierfr** [comment]
For me it seems that we only need the `/catalog` endpoint to serve OPDS stream.
`/skin` and `/catch` are not related to the content but they are used to see the content.

**Comment by veloman-yunkan** [comment]
> For me it seems that we only need the `/catalog` endpoint to serve OPDS stream. `/skin` and `/catch` are not related to the content but they are used to see the content.

That's correct. As long as only serving the OPDS stream is concerned, no doubt `/skin` and `/catch` are unrelated. However I was considering this ticket in a slightly wider context of service uptime and load balancing. I thought that we are now moving towards running multiple containers to serve different types of requests so that one stuck or crashed `kiwix-serve` doesn't bring entire `https://library.kiwix.org` down. I imagined that eventually different sets (e.g. categories, languages)  of ZIM files would be served by dedicated containers. From that point to view grouping `/skin` and `/catch` with `/catalog` makes sense.

**Comment by mgautierfr** [comment]
Load balancing is a interesting feature. But I create the ticket with the idea that people using the "demo" library.kiwix.org doesn't interfere with the mandatory feature of the catalog service.
The plan, for now, is to split this two fundamentally different features in two different process.

**Comment by kelson42** [comment]
> The plan, for now, is to split this two fundamentally different features in two different process.

Sounds good to me (if not too complicated), the approaches are not excluding each other IMO.

**Comment by kelson42** [comment]
@rgaudin We will ahve to carry on this next IMO.

**Comment by rgaudin** [comment]
Done. We now have two independent containers. catalog-only one still accessing ZIMs until aforementioned issue is resolved on libkiwix.
